server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: msvc-student
            uri: http://127.0.0.1:8090
            predicates:
              - Path=/api/student/**

          - id: msvc-course
            uri: http://127.0.0.1:9090
            predicates:
              - Path=/api/course/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"