server {
    listen 80;
    server_name vannisystem.local www.vannisystem.local;

    # --- 1. RUTA AL FRONTEND (ANGULAR) ---
    # Cuando alguien entre a http://vannisystem.local/ lo mandamos al contenedor de Angular
    location / {
        proxy_pass http://angular-front-app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- 2. RUTA AL API GATEWAY (SPRING BACKEND) ---
    # Cuando Angular mande peticiones que arranquen con /api/, Nginx las redirige al Gateway
    location /api/ {
        proxy_pass http://microservice-gateway-app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- 3. RUTA AL PANEL DE EUREKA (OPCIONAL) ---
    # Por si quieres ver tus microservicios desde http://vannisystem.local/eureka-dashboard/
    location /eureka-dashboard/ {
        proxy_pass http://microservice-eureka-server:8761/;
        proxy_set_header Host $host;
    }
}